# Parameters used to generate this project with aem-project-archetype

groupId=com.empire.shared
artifactId=empire-shared
version=1.0.0-SNAPSHOT
package=com.empire.shared
appId=empire-shared
appTitle=Empire Shared
aemVersion=cloud
sdkVersion=latest
languageCountry=${languageCountry}
includeExamples=n
includeErrorHandler=n
frontendModule=general
singleCountry=y
includeDispatcherConfig=y
includeCif=n
includeForms=n
includeFormsenrollment=n
includeFormscommunications=n
sdkFormsVersion=latest
commerceEndpoint=https://hostname.com/graphql
datalayer=y
amp=n
enableDynamicMedia=n
enableSSR=n
precompiledScripts=n
includeFormsheadless=n
uiTestingFramework=cypress
